added event
lv-381-java/Actent pull request #42
Opened 2019-03-04 17:46 UTC by RBarnabass

2019-03-04 20:26 UTC, thebadpanda approved these changes

2019-03-04 22:25 UTC, md1guy requested changes

2019-03-04 22:25 UTC, md1guy commented on src/main/java/com/softserve/actent/model/entity/Event.java
> +    @Column(length = 500)
Remove magic string and length restriction.

2019-03-04 22:25 UTC, md1guy commented on src/main/java/com/softserve/actent/model/entity/Event.java
> +    @Column(nullable = false, length = 100)
Remove magic string and length restriction.

2019-03-05 07:38 UTC, md1guy approved these changes

2019-03-05 09:21 UTC, onlyVone-zz approved these changes

2019-03-05 10:01 UTC, merged